services:
  scheduler:
    build: .
    container_name: household-scheduler-app
    restart: unless-stopped
    ports:
      - "3400:3400"
    environment:
      - NODE_ENV=production
      - PORT=3400
      - HOSTNAME=0.0.0.0
    volumes:
      - ./db:/app/db